---
title: "New York State Politics and Government Structure"
subtitle: "Spring 2023"
author: "Don Boyd, Professor-in-Residence"
institute: New York State Assembly Intern Program
date: today
date-format: long
format:
  revealjs: 
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
  pdf:
    toc: false
execute:
  echo: true    
---

## Goal: Practical Knowledge for Operating in the NY Environment {.smaller}

-   My background
    -   6 years Assembly Ways & Means (taxes/fiscal)
    -   8 years NY Budget Division (economy/fiscal/taxes)
    -   22 years Rockefeller Institute - gov't finances in U.S.
    -   State Budget Crisis Task Force (ED)
    -   \~5-year interlude: academic research on teacher characteristics, teacher labor markets, & student academic performance
    -   fiscal & economic consulting - federal, state, & local govt's; think tanks; industry groups, trade associations, and advocacy organizations; unions
-   Your background, interests, goals?

<!--
Publishing to the web

quarto publish netlify context.qmd
# quarto publish netlify --no-render --no-browser --no-prompt
# quarto publish netlify --no-browser --no-prompt

https://boyd-context.netlify.app

# quarto render context.qmd --to html
# quarto render context.qmd --to pdf


  pdf:
    toc: true
    toc-depth: 2
    documentclass: report # scrreprt scrartcl report

-->



## About the Course (1) {.smaller}

-   3 lectures:

    -   The Context for Policymaking in New York

    -   Federalism - who does what and why? how do governments interact?

    -   Who makes law and policy?

-   2-minute presentations:

    -   Describe and analyze a proposal or issue

    -   A crucial skill

    -   Every presentation is a job interview

## About the Course (2) {.smaller}

-   10-minute skills (1 per lecture) - examples:

    -   How to get advice from an expert

    -   How to give advice to a non-expert

    -   How to ask questions of an academic

    -   How to make a mistake

    -   How to keep the ball rolling

## About the Course (3) {.smaller}

-   We cannot possibly cover important elements of the 3 lectures, in depth, in an 85 minute class.

-   I will try, in the slides, to give depth and real-world illustrations. You do not need to memorize these.

-   I will try to give links that allow you to explore the issues and illustrations more deeply. You will be your own best teacher.

## Grading

-   No quizzes

-   Attendance; I expect participation

-   I'll be grading papers of students who have me in Cycle 1 -- groups C and F

## The Paper {.smaller}

Whenever you write anything, ask (1) Who's the audience?, (2) What's the purpose? Here, they are two-fold:

-   An Assemblymember who wants a full 360 degrees view of a proposal

-   A public policy-interested audience with time to dig in, wants details & sources

I am looking for:

-   1-page up-front summary (Assemblymembers are busy, must split their attention)

-   Describe and analyze the *proposal* (esp. bill language), not just the *issue*. Heard often:

> *Vote on the bill, not the memo.*

-   Be rigorous: Document your analysis, draw on original sources & cite them.

-   Be concise and clear: **writing is rewriting**. (Strunk & White is on Moodle, FYI.)

## Optional {.smaller}

-   Your interests - If you would like, please write 1 short paragraph that mentions a policy issue or two that you're interested in, or what you want to get out of the course or program. This will help me think about illustrations and resources for future lectures.

-   Feedback - I would like anonymous feedback from students willing to offer it

    -   Would appreciate it if, after each lecture, one student can gather comments and copy into [Google doc](https://docs.google.com/document/d/1ymJzG2t4sdk8OEuFKtG7LoNw2M9ntNwTbSB9YDwH7WI/edit?usp=sharing)

    -   Ideally commenters will address tersely up to 3 questions about the lecture:

        1.  What was good?

        2.  What was bad?

        3.  What is 1 change that would improve it?

## Slide logistics {.smaller}

-   My slides are in reveal.js format. It doesn't convert easily or well to Powerpoint or landscape pdfs.

-   Slides will have links and information that I hope will be useful to you. I will do two things to try to make them accessible:

    -   Create a pdf of the slides in portrait mode and put them on Moodle. So far, these conversions are working pretty well - this document is done that way - but no guarantees for the future.
    
    -   Put the substantive slides (not this doc) on the web as html so you can access them that way. That will work well, but you probably won't be able to save them to pdf in a usable form from the web.
    

