---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Approach to the course

We will learn about the legislative process and analyzing legislation by examining a single issue and related proposed legislation. We will have group discussions and brief presentations. You will need to come to class prepared.

We will examine two 2023 proposals designed to raise significant revenue from wealthy or high-income individuals: a brand-new tax on billionaires, and a millionaires' tax. These proposals provide us with rich opportunities to explore questions of inequality, tax progressivity, economic and fiscal consequences of legislation, the practicalities and importance of implementation, and the views of proponents and opponents. In no way will I argue for or against either bill. My job is to lead us in examining them from multiple sides, and to help you develop knowledge and skills for doing that.

In addition, in each class we will have a brief vignette on a timely legislative topic (e.g., the state budget).

**Each student will make a 2-minute presentation to the class on a legislative proposal of their choosing, examining it from multiple perspectives. Approximately 7 students will present in each class. See the assignment for details.**
 

## Learning objectives

-   How to identify and analyze key issues underlying proposed legislation

-   How to identify and analyze how proposed legislation addresses the issues

-   How to parse and understand legislation in detail

-   How to evaluate the quality of evidence, and be appropriately skeptical

-   How to present a balanced and concise summary of a legislative proposal and the key issues it raises


## Groups for group discussions

