# Introduction

Describing and analyzing proposals and speaking succinctly about them in a public forum are crucial skills.

In this course each of you will have at least one opportunity to speak before your classmates for two minutes on a public policy issue.

There are 26 students, we have 4 classes, so we'll have approximately x students per calls. I have chosen a schedule at random **\[schedule\]**:

In each class, approximately x students will present early in the class, then we\'ll have the lecture and group work, and then the other approximately x students will present.

To present, you\'ll come up to the front of the class and speak, using notes (electronic or paper) if you want. **Strictly verbal - no Powerpoint presentations or anything similar.**

You'll start a 2-minute timer when you start, and you MUST stop speaking when it goes off. After that, you'll be in charge:

-   Call sequentially on 2 students who will ask substantive questions about the proposal, and give your responses. Try to call on people who haven't asked questions already.

-   Take a minute to critique your performance:

    -   Did you allocate time to the sub-topics in a way that worked well?

    -   Did you leave important things out?

    -   Did you include unnecessary information?

    -   What would you do differently if you were doing it again?

-   

# The Situation

·       An Assembly member wants a high-level understanding of a bill they will eventually have to vote on -- what it does, the issue it\'s addressing, pros, cons, who\'s for & who\'s against and why, issues and risks, and what\'s important to know that we don\'t yet know.

·       You only have 2 minutes to tell the Assembly member the **most important things** they need to know about the legislation.

o   This really could happen for an initial briefing -- the member could have a full day of meetings and ask you to stop in their office between meetings, or they might ask you to walk with them on their way to the Assembly chamber.

·       You need to organize your thoughts, figure out what is most important, and deliver in an organized way.

·       This is a briefing in early stages. You\'re not giving a recommendation at this point.

·       In the exercise, regardless of whether you are pro or con in real life, YOU ARE AN ANALYST, NOT AN ADVOCATE. You need to let the member know the most important arguments for and against. Regardless of your personal views on the issue, it\'s always important for the Assembly member to also know the arguments on the other side -- they will be hit with them by constituents, advocates, and other members and need to understand them.

THIS IS NOT A RESEARCH  PROJECT. YOU DON\'T HAVE TO KNOW EVERYTHING. BUT IF YOU DON\'T KNOW SOMETHING IMPORTANT, YOU SHOULD FLAG IT AS AN UNCERTAINTY AND AN ISSUE FOR FOLLOW UP. (You don\'t have to follow up for this make-believe assignment, of course.)

Please do not spend more than about an hour or so preparing for this.

# The Assignment

·       Speak for **NO MORE THAN 2 MINUTES** on an important NY legislative proposal of your choosing. It can be your research paper topic if you like.

·       You\'re trying to provide broad and balanced information to **first**, help the Assembly member understand the proposal, and **ultimately** help them decide what they want to do about it, although they\'ll make that decision later. (You can\'t possibly give them enough information for that in this initial presentation. They\'ll probably pepper you with questions you can\'t answer initially.)

·       For the issue you have selected discuss most of the following items, making choices needed to keep your talk within **TWO MINUTES**:

o   What is the proposal and what would it do? **THIS IS ESSENTIAL**.

o   What issue does it address? (Integrate with the above.)

o   Who's for it and why?

o   Who\'s against it and why?

o   Major issues and risks

o   Concluding comments and/or any next steps you think you should pursue

·       Regarding **Who\'s for it and why**:

o   You may have to pick a single large component of the proposal, because people may be for some elements of the proposal and against others. For example, you might say, \"The most controversial element of the proposal is X\" and describe opinions in relation to X, where you, of course say what X is.

o   By \"who\" I mean major players in the legislative process -- it could be a business group, a nonprofit advocacy organization, a union, the mayor of a large city, or some other prominent organization or leader.

o   **Be specific** -- it\'s not enough to say, \"I think medical providers will be in favor of this because it might lower their costs\". It is better to say, \"the Greater New York Hospital Association, which represents the major hospitals and health care systems in New York and the surrounding region, is strongly in favor -- they say it will get rid of unnecessary regulations and improve patient care.\"

o   **Recognize nuance**, if you can: \"Major patient-care advocacy organizations dispute GNYHA\'s point that eliminating these regulations will improve patient care. Those regulations were put in place in response to scandal X.\"

o   In this, as in all things analytical, **be skeptical**: people often give public reasons for favoring or opposing a proposal that differ from their real reasons. Your job is NOT to assert that they are doing this. You always should give their stated reasons -- they are important to know, even if you don\'t believe the reasons, or even if there are more-important unstated reasons. But where you know that proponents or opponents face incentives consistent with additional or alternative reasons, it is important to point that out.

o   You can certainly describe multiple groups\' opinions on the issue, remembering, always, that your goal is to use your 2 minutes wisely.

·       Who's against it and why? -- same guidance as for \"Who\'s for...\".

·       **Uncertainties and next steps**: Give the Assemblymember any concluding comments you think they should have. For example, let them know crucial next steps: \"It\'s really critical for you to understand X but I couldn\'t answer that question yet. I\'m looking into it by doing Y.\"

·       **Stick to facts and statements you can verify**. As important as your opinion is, at this stage the Assemblymember needs your analysis, not your advocacy.

·       **Decide what\'s most important**: You will not have time to address all of the above. YOU will have to decide what is most important for the Assemblymember to hear at this point in the decision making process, which is early. (In this hypothetical example, you would have time to follow up afterward.)

·       You cannot know answers to all relevant questions at this stage. **I do not want this to be a research project.** When you cannot answer a question, but you know it\'s important, then you should let the Assemblymember know it is an important question and you intend to investigate it.

·       **DO NOT GO OVER 2 MINUTES**. We\'ll have a timer. It is far worse to run out of time and leave out key concluding comments and next steps than it is to leave out some details.

# After your two minutes

·       We\'ll have time for 1-2 questions from classmates. Your classmates will be legislators who will have to vote on this proposal and may want to steer its direction. They may ask you questions you have not thought about, which is fine.

·       Give a comment or two on what you might do differently if you were doing it again, to give the best-possible 2-minute briefing. Did you leave something important out? Did you put something in that wasn\'t important?
