---
output: pdf_document  # or word_document
title: "`r paste0(params$student, ', Research paper final grade')`"
subtitle: "New York State Assembly Intern Program, 2024: Comments from Professor Don Boyd"
date: "`r format(Sys.time(), '%B %d, %Y')`"
params:
  student: "Default student name"
  billnum: "Default bill number"
  billdesc: "Default bill description"
  gradebase: "To come"
  comments: ""
  policy: "Default policy"
  policy_points: ""
  politics: "Default politics"
  politics_points: ""
  democracy: "Default democracy"
  democracy_points: "" 
  research: "Default research"
  research_points: "" 
  writing: "Default writing"
  writing_points: "" 
  ppd_pct: ""
  research_pct: ""
  writing_pct: ""
---

# How to interpret your grade

This document summarizes your grade on the final research paper before considering any possible late penalties. Your final grade will consist of this grade, less any late penalties that apply.

Your grade before penalties on a scale of 0-100 is in the section, *Overall grade before any late penalties*.

It is calculated as follows: I graded each of 5 categories on a 10-point scale: policy analysis, political analysis, democracy analysis, research quality, and writing quality. The categories are weighted as follows:

-   Policy, political, and democracy analysis combined are worth `r label_percent()(params$ppd_pct)` (each is worth one-third of that, or approximately  `r label_percent(accuracy=.1)(params$ppd_pct / 3)`).
-   Research quality is weighted `r label_percent()(params$research_pct)`
-   Writing quality is weighted `r label_percent()(params$writing_pct)`

The weighted sum of your points, multiplied by 10 to put it on a 100-point scale, is your overall grade before any late penalties.

# Bill number and short description

`r paste0(params$billnum, ": ", params$billdesc, ".  ")`

# Overall grade before any late penalties

`r paste0("**Grade: ", label_number(accuracy=.1)(params$gradebase), " out of 100 possible.**\n")`
`r if(!is.na(params$comments)) params$comments`

# Policy analysis

`r paste0("Points: ", params$policy_points, " out of 10 possible.\n")`
`r params$policy`

# Political analysis

`r paste0("Points: ", params$politics_points, " out of 10 possible.\n")`
`r params$politics`

# Democracy analysis

`r paste0("Points: ", params$democracy_points, " out of 10 possible.\n")`
`r params$democracy`

# Research quality

`r paste0("Points: ", params$research_points, " out of 10 possible.\n")`
`r params$research`

# Writing quality

`r paste0("Points: ", params$writing_points, " out of 10 possible.\n")`
`r params$writing`

