
# Planning and Todos


## Janet's notes from October Zoom call

1. Each of our "classes" would be called a "module" of which there would be three:
   Democracy: Angela
   Policy: Don
   Politics: Janet and Nick

2. Each professor would be responsible for course development, determining assignments for grading, and grading their assigned student's work.

3. A combined syllabus would be developed to include each module's course description, requirements and so forth, followed by a sub-syllabus for each the three modules.

4. Each module would be comprised of 4 classes with a joint lecture to be held on February 14th.

5. Each student would be tasked to produce the following IN ADDITION to each professor's requirements for their module:
   a. A district analysis.
   b. An annotated bibliography as a prelude to the final paper.
   c. An outline of a research proposal for the final paper to include an outline for all 3 sections of the paper.

We adjourned the meeting with the following "to do" list:

1. Each professor to produce their sub-syllabus.  From there the group would:
         a. Produce a unified syllabus that draws together each of the modules and gives the students an overview of the whole.
         b. Review and finalize assignments the for the district analysis, annotated bibliography, and outline of a research proposal.

2. Finalize the calendar for the semester.

3. Plan the orientation schedule.

4. Develop grading rubrics and system for individual assignment grades that would calculate a final grade at the end of the semester.


## Janet's notes from November 6 Zoom call

1.  Class times:
    Janet & Nick:  9:30-11:00
    Angela:        11:00-12:30
    Don:           1:00-2:30

2.  Grading:
    Office Experience: 30%
    Practicum: 15%
    Final paper proposal with annotated bibliography: 10%
    District characteristics short paper:  5%
    Individual module assignment: 10%
    Final paper: 30%

3. Each professor, by December 10th, will produce a description of their individual modules to include a one paragraph overview, assignments and grading, and reading list. Each module will follow a common theme: the millionaire's tax/taxes on high income earners.

4.  Janet to write first draft of a syllabus incorporating each module description, including a course overview and learning objectives.
5.  Angela to draft instructions for research proposal and annotated bibliography for final paper.
6.  Janet will edit instructions for district characteristics short paper, omitting requirements for graphs.
7.  Don and Janet to produce shared grading spreadsheet.
8.  Nick and Janet to produce a shared working calendar for academic class dates, practicum workshops, and due dates.
9.  Everyone will review instructions the final paper and suggest revisions.  Equal grading weight for each section.


