project:
  type: book

# quarto publish netlify --no-render
# quarto publish netlify --no-browser --no-prompt
# quarto publish netlify --no-render --no-browser --no-prompt

# https://quarto.org/docs/computations/execution-options.html    
# for cell options: https://quarto.org/docs/reference/cells/cells-knitr.html
# execute:
#   freeze: auto  # re-render only when source changes
execute:
  eval: true
  echo: false
  error: false
  warning: false
  message: false  # not sure if allowed
  note: false  # not sure if allowed
  freeze: auto  # during global project renders, re-render only when source changes
  
# The computational results of documents executed with freeze are stored in the
# _freeze directory, and re-used when needed to fulfill document renders. You
# should check the contents of _freeze into version control so that others 
# rendering the project don’t need to reproduce your computational environment
# to render it in their environment.  
  
editor_options: 
  chunk_output_type: console

book:
  title: "Assembly Intern Program"
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - notes.qmd
    # - part: "Baseline"
    #   chapters:
    #   - intro/goals.qmd
    #   - intro/boyd_questions.qmd
    # - bibliography.qmd      

# bibliography: _baseline.bib
# nocite: |
#   @*

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt
